// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: otrader_engine.proto

#include "otrader_engine.pb.h"
#include "otrader_engine.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace otrader {

static const char* EngineService_method_names[] = {
  "/otrader.EngineService/GetStatus",
  "/otrader.EngineService/ListStrategies",
  "/otrader.EngineService/ConnectGateway",
  "/otrader.EngineService/DisconnectGateway",
  "/otrader.EngineService/StartMarketData",
  "/otrader.EngineService/StopMarketData",
  "/otrader.EngineService/StartStrategy",
  "/otrader.EngineService/StopStrategy",
  "/otrader.EngineService/StreamLogs",
  "/otrader.EngineService/StreamStrategyUpdates",
  "/otrader.EngineService/GetOrdersAndTrades",
  "/otrader.EngineService/ListPortfolios",
  "/otrader.EngineService/ListStrategyClasses",
  "/otrader.EngineService/GetStrategyClassDefaults",
  "/otrader.EngineService/GetPortfoliosMeta",
  "/otrader.EngineService/GetRemovedStrategies",
  "/otrader.EngineService/AddStrategy",
  "/otrader.EngineService/RestoreStrategy",
  "/otrader.EngineService/InitStrategy",
  "/otrader.EngineService/RemoveStrategy",
  "/otrader.EngineService/DeleteStrategy",
  "/otrader.EngineService/GetStrategyHoldings",
  "/otrader.EngineService/StartBacktest",
  "/otrader.EngineService/SendCommand",
};

std::unique_ptr< EngineService::Stub> EngineService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< EngineService::Stub> stub(new EngineService::Stub(channel, options));
  return stub;
}

EngineService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetStatus_(EngineService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListStrategies_(EngineService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ConnectGateway_(EngineService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DisconnectGateway_(EngineService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StartMarketData_(EngineService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopMarketData_(EngineService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StartStrategy_(EngineService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StopStrategy_(EngineService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamLogs_(EngineService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_StreamStrategyUpdates_(EngineService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_GetOrdersAndTrades_(EngineService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListPortfolios_(EngineService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListStrategyClasses_(EngineService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStrategyClassDefaults_(EngineService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPortfoliosMeta_(EngineService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRemovedStrategies_(EngineService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddStrategy_(EngineService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RestoreStrategy_(EngineService_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_InitStrategy_(EngineService_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RemoveStrategy_(EngineService_method_names[19], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteStrategy_(EngineService_method_names[20], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStrategyHoldings_(EngineService_method_names[21], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StartBacktest_(EngineService_method_names[22], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SendCommand_(EngineService_method_names[23], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::Status EngineService::Stub::GetStatus(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::EngineStatus* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::EngineStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStatus_, context, request, response);
}

void EngineService::Stub::async::GetStatus(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::EngineStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::EngineStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStatus_, context, request, response, std::move(f));
}

void EngineService::Stub::async::GetStatus(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::EngineStatus* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::EngineStatus>* EngineService::Stub::PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::EngineStatus, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::EngineStatus>* EngineService::Stub::AsyncGetStatusRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::otrader::StrategySummary>* EngineService::Stub::ListStrategiesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::otrader::StrategySummary>::Create(channel_.get(), rpcmethod_ListStrategies_, context, request);
}

void EngineService::Stub::async::ListStrategies(::grpc::ClientContext* context, const ::otrader::Empty* request, ::grpc::ClientReadReactor< ::otrader::StrategySummary>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::otrader::StrategySummary>::Create(stub_->channel_.get(), stub_->rpcmethod_ListStrategies_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::otrader::StrategySummary>* EngineService::Stub::AsyncListStrategiesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::StrategySummary>::Create(channel_.get(), cq, rpcmethod_ListStrategies_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::otrader::StrategySummary>* EngineService::Stub::PrepareAsyncListStrategiesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::StrategySummary>::Create(channel_.get(), cq, rpcmethod_ListStrategies_, context, request, false, nullptr);
}

::grpc::Status EngineService::Stub::ConnectGateway(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ConnectGateway_, context, request, response);
}

void EngineService::Stub::async::ConnectGateway(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectGateway_, context, request, response, std::move(f));
}

void EngineService::Stub::async::ConnectGateway(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectGateway_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::PrepareAsyncConnectGatewayRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ConnectGateway_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::AsyncConnectGatewayRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConnectGatewayRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::DisconnectGateway(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DisconnectGateway_, context, request, response);
}

void EngineService::Stub::async::DisconnectGateway(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DisconnectGateway_, context, request, response, std::move(f));
}

void EngineService::Stub::async::DisconnectGateway(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DisconnectGateway_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::PrepareAsyncDisconnectGatewayRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DisconnectGateway_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::AsyncDisconnectGatewayRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDisconnectGatewayRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::StartMarketData(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartMarketData_, context, request, response);
}

void EngineService::Stub::async::StartMarketData(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartMarketData_, context, request, response, std::move(f));
}

void EngineService::Stub::async::StartMarketData(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartMarketData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::PrepareAsyncStartMarketDataRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartMarketData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::AsyncStartMarketDataRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartMarketDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::StopMarketData(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StopMarketData_, context, request, response);
}

void EngineService::Stub::async::StopMarketData(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopMarketData_, context, request, response, std::move(f));
}

void EngineService::Stub::async::StopMarketData(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopMarketData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::PrepareAsyncStopMarketDataRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StopMarketData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::AsyncStopMarketDataRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopMarketDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::StartStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::StrategyNameRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartStrategy_, context, request, response);
}

void EngineService::Stub::async::StartStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::StrategyNameRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartStrategy_, context, request, response, std::move(f));
}

void EngineService::Stub::async::StartStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::PrepareAsyncStartStrategyRaw(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::StrategyNameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::AsyncStartStrategyRaw(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::StopStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::StrategyNameRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StopStrategy_, context, request, response);
}

void EngineService::Stub::async::StopStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::StrategyNameRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopStrategy_, context, request, response, std::move(f));
}

void EngineService::Stub::async::StopStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StopStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::PrepareAsyncStopStrategyRaw(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::StrategyNameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StopStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::AsyncStopStrategyRaw(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::otrader::LogLine>* EngineService::Stub::StreamLogsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::otrader::LogLine>::Create(channel_.get(), rpcmethod_StreamLogs_, context, request);
}

void EngineService::Stub::async::StreamLogs(::grpc::ClientContext* context, const ::otrader::Empty* request, ::grpc::ClientReadReactor< ::otrader::LogLine>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::otrader::LogLine>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamLogs_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::otrader::LogLine>* EngineService::Stub::AsyncStreamLogsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::LogLine>::Create(channel_.get(), cq, rpcmethod_StreamLogs_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::otrader::LogLine>* EngineService::Stub::PrepareAsyncStreamLogsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::LogLine>::Create(channel_.get(), cq, rpcmethod_StreamLogs_, context, request, false, nullptr);
}

::grpc::ClientReader< ::otrader::StrategyUpdate>* EngineService::Stub::StreamStrategyUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::otrader::StrategyUpdate>::Create(channel_.get(), rpcmethod_StreamStrategyUpdates_, context, request);
}

void EngineService::Stub::async::StreamStrategyUpdates(::grpc::ClientContext* context, const ::otrader::Empty* request, ::grpc::ClientReadReactor< ::otrader::StrategyUpdate>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::otrader::StrategyUpdate>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamStrategyUpdates_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::otrader::StrategyUpdate>* EngineService::Stub::AsyncStreamStrategyUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::StrategyUpdate>::Create(channel_.get(), cq, rpcmethod_StreamStrategyUpdates_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::otrader::StrategyUpdate>* EngineService::Stub::PrepareAsyncStreamStrategyUpdatesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::StrategyUpdate>::Create(channel_.get(), cq, rpcmethod_StreamStrategyUpdates_, context, request, false, nullptr);
}

::grpc::Status EngineService::Stub::GetOrdersAndTrades(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::OrdersAndTradesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::OrdersAndTradesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetOrdersAndTrades_, context, request, response);
}

void EngineService::Stub::async::GetOrdersAndTrades(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::OrdersAndTradesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::OrdersAndTradesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOrdersAndTrades_, context, request, response, std::move(f));
}

void EngineService::Stub::async::GetOrdersAndTrades(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::OrdersAndTradesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetOrdersAndTrades_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::OrdersAndTradesResponse>* EngineService::Stub::PrepareAsyncGetOrdersAndTradesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::OrdersAndTradesResponse, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetOrdersAndTrades_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::OrdersAndTradesResponse>* EngineService::Stub::AsyncGetOrdersAndTradesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetOrdersAndTradesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::ListPortfolios(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::ListPortfoliosResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::ListPortfoliosResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListPortfolios_, context, request, response);
}

void EngineService::Stub::async::ListPortfolios(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::ListPortfoliosResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::ListPortfoliosResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListPortfolios_, context, request, response, std::move(f));
}

void EngineService::Stub::async::ListPortfolios(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::ListPortfoliosResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListPortfolios_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::ListPortfoliosResponse>* EngineService::Stub::PrepareAsyncListPortfoliosRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::ListPortfoliosResponse, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListPortfolios_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::ListPortfoliosResponse>* EngineService::Stub::AsyncListPortfoliosRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListPortfoliosRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::ListStrategyClasses(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::ListStrategyClassesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::ListStrategyClassesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListStrategyClasses_, context, request, response);
}

void EngineService::Stub::async::ListStrategyClasses(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::ListStrategyClassesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::ListStrategyClassesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListStrategyClasses_, context, request, response, std::move(f));
}

void EngineService::Stub::async::ListStrategyClasses(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::ListStrategyClassesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListStrategyClasses_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::ListStrategyClassesResponse>* EngineService::Stub::PrepareAsyncListStrategyClassesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::ListStrategyClassesResponse, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListStrategyClasses_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::ListStrategyClassesResponse>* EngineService::Stub::AsyncListStrategyClassesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListStrategyClassesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::GetStrategyClassDefaults(::grpc::ClientContext* context, const ::otrader::GetStrategyClassDefaultsRequest& request, ::otrader::GetStrategyClassDefaultsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::GetStrategyClassDefaultsRequest, ::otrader::GetStrategyClassDefaultsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStrategyClassDefaults_, context, request, response);
}

void EngineService::Stub::async::GetStrategyClassDefaults(::grpc::ClientContext* context, const ::otrader::GetStrategyClassDefaultsRequest* request, ::otrader::GetStrategyClassDefaultsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::GetStrategyClassDefaultsRequest, ::otrader::GetStrategyClassDefaultsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStrategyClassDefaults_, context, request, response, std::move(f));
}

void EngineService::Stub::async::GetStrategyClassDefaults(::grpc::ClientContext* context, const ::otrader::GetStrategyClassDefaultsRequest* request, ::otrader::GetStrategyClassDefaultsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStrategyClassDefaults_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::GetStrategyClassDefaultsResponse>* EngineService::Stub::PrepareAsyncGetStrategyClassDefaultsRaw(::grpc::ClientContext* context, const ::otrader::GetStrategyClassDefaultsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::GetStrategyClassDefaultsResponse, ::otrader::GetStrategyClassDefaultsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStrategyClassDefaults_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::GetStrategyClassDefaultsResponse>* EngineService::Stub::AsyncGetStrategyClassDefaultsRaw(::grpc::ClientContext* context, const ::otrader::GetStrategyClassDefaultsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStrategyClassDefaultsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::GetPortfoliosMeta(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::ListPortfoliosResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::ListPortfoliosResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPortfoliosMeta_, context, request, response);
}

void EngineService::Stub::async::GetPortfoliosMeta(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::ListPortfoliosResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::ListPortfoliosResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPortfoliosMeta_, context, request, response, std::move(f));
}

void EngineService::Stub::async::GetPortfoliosMeta(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::ListPortfoliosResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPortfoliosMeta_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::ListPortfoliosResponse>* EngineService::Stub::PrepareAsyncGetPortfoliosMetaRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::ListPortfoliosResponse, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPortfoliosMeta_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::ListPortfoliosResponse>* EngineService::Stub::AsyncGetPortfoliosMetaRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPortfoliosMetaRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::GetRemovedStrategies(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::GetRemovedStrategiesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::GetRemovedStrategiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRemovedStrategies_, context, request, response);
}

void EngineService::Stub::async::GetRemovedStrategies(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::GetRemovedStrategiesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::GetRemovedStrategiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRemovedStrategies_, context, request, response, std::move(f));
}

void EngineService::Stub::async::GetRemovedStrategies(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::GetRemovedStrategiesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRemovedStrategies_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::GetRemovedStrategiesResponse>* EngineService::Stub::PrepareAsyncGetRemovedStrategiesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::GetRemovedStrategiesResponse, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRemovedStrategies_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::GetRemovedStrategiesResponse>* EngineService::Stub::AsyncGetRemovedStrategiesRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRemovedStrategiesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::AddStrategy(::grpc::ClientContext* context, const ::otrader::AddStrategyRequest& request, ::otrader::AddStrategyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::AddStrategyRequest, ::otrader::AddStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddStrategy_, context, request, response);
}

void EngineService::Stub::async::AddStrategy(::grpc::ClientContext* context, const ::otrader::AddStrategyRequest* request, ::otrader::AddStrategyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::AddStrategyRequest, ::otrader::AddStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddStrategy_, context, request, response, std::move(f));
}

void EngineService::Stub::async::AddStrategy(::grpc::ClientContext* context, const ::otrader::AddStrategyRequest* request, ::otrader::AddStrategyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::AddStrategyResponse>* EngineService::Stub::PrepareAsyncAddStrategyRaw(::grpc::ClientContext* context, const ::otrader::AddStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::AddStrategyResponse, ::otrader::AddStrategyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::AddStrategyResponse>* EngineService::Stub::AsyncAddStrategyRaw(::grpc::ClientContext* context, const ::otrader::AddStrategyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::RestoreStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::StrategyNameRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RestoreStrategy_, context, request, response);
}

void EngineService::Stub::async::RestoreStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::StrategyNameRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RestoreStrategy_, context, request, response, std::move(f));
}

void EngineService::Stub::async::RestoreStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RestoreStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::PrepareAsyncRestoreStrategyRaw(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::StrategyNameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RestoreStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::AsyncRestoreStrategyRaw(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRestoreStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::InitStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::otrader::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::StrategyNameRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_InitStrategy_, context, request, response);
}

void EngineService::Stub::async::InitStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::StrategyNameRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InitStrategy_, context, request, response, std::move(f));
}

void EngineService::Stub::async::InitStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_InitStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::PrepareAsyncInitStrategyRaw(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::Empty, ::otrader::StrategyNameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_InitStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::Empty>* EngineService::Stub::AsyncInitStrategyRaw(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInitStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::RemoveStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::otrader::RemoveStrategyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::StrategyNameRequest, ::otrader::RemoveStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RemoveStrategy_, context, request, response);
}

void EngineService::Stub::async::RemoveStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::RemoveStrategyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::StrategyNameRequest, ::otrader::RemoveStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RemoveStrategy_, context, request, response, std::move(f));
}

void EngineService::Stub::async::RemoveStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::RemoveStrategyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RemoveStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::RemoveStrategyResponse>* EngineService::Stub::PrepareAsyncRemoveStrategyRaw(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::RemoveStrategyResponse, ::otrader::StrategyNameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RemoveStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::RemoveStrategyResponse>* EngineService::Stub::AsyncRemoveStrategyRaw(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRemoveStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::DeleteStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::otrader::DeleteStrategyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::StrategyNameRequest, ::otrader::DeleteStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteStrategy_, context, request, response);
}

void EngineService::Stub::async::DeleteStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::DeleteStrategyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::StrategyNameRequest, ::otrader::DeleteStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteStrategy_, context, request, response, std::move(f));
}

void EngineService::Stub::async::DeleteStrategy(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::DeleteStrategyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteStrategy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::DeleteStrategyResponse>* EngineService::Stub::PrepareAsyncDeleteStrategyRaw(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::DeleteStrategyResponse, ::otrader::StrategyNameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteStrategy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::DeleteStrategyResponse>* EngineService::Stub::AsyncDeleteStrategyRaw(::grpc::ClientContext* context, const ::otrader::StrategyNameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteStrategyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status EngineService::Stub::GetStrategyHoldings(::grpc::ClientContext* context, const ::otrader::Empty& request, ::otrader::StrategyHoldingsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::otrader::Empty, ::otrader::StrategyHoldingsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStrategyHoldings_, context, request, response);
}

void EngineService::Stub::async::GetStrategyHoldings(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::StrategyHoldingsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::otrader::Empty, ::otrader::StrategyHoldingsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStrategyHoldings_, context, request, response, std::move(f));
}

void EngineService::Stub::async::GetStrategyHoldings(::grpc::ClientContext* context, const ::otrader::Empty* request, ::otrader::StrategyHoldingsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStrategyHoldings_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::otrader::StrategyHoldingsResponse>* EngineService::Stub::PrepareAsyncGetStrategyHoldingsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::otrader::StrategyHoldingsResponse, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStrategyHoldings_, context, request);
}

::grpc::ClientAsyncResponseReader< ::otrader::StrategyHoldingsResponse>* EngineService::Stub::AsyncGetStrategyHoldingsRaw(::grpc::ClientContext* context, const ::otrader::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStrategyHoldingsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::otrader::EngineStateUpdate>* EngineService::Stub::StartBacktestRaw(::grpc::ClientContext* context, const ::otrader::StreamRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::otrader::EngineStateUpdate>::Create(channel_.get(), rpcmethod_StartBacktest_, context, request);
}

void EngineService::Stub::async::StartBacktest(::grpc::ClientContext* context, const ::otrader::StreamRequest* request, ::grpc::ClientReadReactor< ::otrader::EngineStateUpdate>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::otrader::EngineStateUpdate>::Create(stub_->channel_.get(), stub_->rpcmethod_StartBacktest_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::otrader::EngineStateUpdate>* EngineService::Stub::AsyncStartBacktestRaw(::grpc::ClientContext* context, const ::otrader::StreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::EngineStateUpdate>::Create(channel_.get(), cq, rpcmethod_StartBacktest_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::otrader::EngineStateUpdate>* EngineService::Stub::PrepareAsyncStartBacktestRaw(::grpc::ClientContext* context, const ::otrader::StreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::otrader::EngineStateUpdate>::Create(channel_.get(), cq, rpcmethod_StartBacktest_, context, request, false, nullptr);
}

::grpc::ClientWriter< ::otrader::CommandRequest>* EngineService::Stub::SendCommandRaw(::grpc::ClientContext* context, ::otrader::CommandAck* response) {
  return ::grpc::internal::ClientWriterFactory< ::otrader::CommandRequest>::Create(channel_.get(), rpcmethod_SendCommand_, context, response);
}

void EngineService::Stub::async::SendCommand(::grpc::ClientContext* context, ::otrader::CommandAck* response, ::grpc::ClientWriteReactor< ::otrader::CommandRequest>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::otrader::CommandRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_SendCommand_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::otrader::CommandRequest>* EngineService::Stub::AsyncSendCommandRaw(::grpc::ClientContext* context, ::otrader::CommandAck* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::otrader::CommandRequest>::Create(channel_.get(), cq, rpcmethod_SendCommand_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::otrader::CommandRequest>* EngineService::Stub::PrepareAsyncSendCommandRaw(::grpc::ClientContext* context, ::otrader::CommandAck* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::otrader::CommandRequest>::Create(channel_.get(), cq, rpcmethod_SendCommand_, context, response, false, nullptr);
}

EngineService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::Empty, ::otrader::EngineStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::EngineStatus* resp) {
               return service->GetStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< EngineService::Service, ::otrader::Empty, ::otrader::StrategySummary>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::grpc::ServerWriter<::otrader::StrategySummary>* writer) {
               return service->ListStrategies(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::Empty* resp) {
               return service->ConnectGateway(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::Empty* resp) {
               return service->DisconnectGateway(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::Empty* resp) {
               return service->StartMarketData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::Empty, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::Empty* resp) {
               return service->StopMarketData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::StrategyNameRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::StrategyNameRequest* req,
             ::otrader::Empty* resp) {
               return service->StartStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::StrategyNameRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::StrategyNameRequest* req,
             ::otrader::Empty* resp) {
               return service->StopStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[8],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< EngineService::Service, ::otrader::Empty, ::otrader::LogLine>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::grpc::ServerWriter<::otrader::LogLine>* writer) {
               return service->StreamLogs(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[9],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< EngineService::Service, ::otrader::Empty, ::otrader::StrategyUpdate>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::grpc::ServerWriter<::otrader::StrategyUpdate>* writer) {
               return service->StreamStrategyUpdates(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::Empty, ::otrader::OrdersAndTradesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::OrdersAndTradesResponse* resp) {
               return service->GetOrdersAndTrades(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::Empty, ::otrader::ListPortfoliosResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::ListPortfoliosResponse* resp) {
               return service->ListPortfolios(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::Empty, ::otrader::ListStrategyClassesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::ListStrategyClassesResponse* resp) {
               return service->ListStrategyClasses(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::GetStrategyClassDefaultsRequest, ::otrader::GetStrategyClassDefaultsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::GetStrategyClassDefaultsRequest* req,
             ::otrader::GetStrategyClassDefaultsResponse* resp) {
               return service->GetStrategyClassDefaults(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::Empty, ::otrader::ListPortfoliosResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::ListPortfoliosResponse* resp) {
               return service->GetPortfoliosMeta(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::Empty, ::otrader::GetRemovedStrategiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::GetRemovedStrategiesResponse* resp) {
               return service->GetRemovedStrategies(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::AddStrategyRequest, ::otrader::AddStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::AddStrategyRequest* req,
             ::otrader::AddStrategyResponse* resp) {
               return service->AddStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::StrategyNameRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::StrategyNameRequest* req,
             ::otrader::Empty* resp) {
               return service->RestoreStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::StrategyNameRequest, ::otrader::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::StrategyNameRequest* req,
             ::otrader::Empty* resp) {
               return service->InitStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[19],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::StrategyNameRequest, ::otrader::RemoveStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::StrategyNameRequest* req,
             ::otrader::RemoveStrategyResponse* resp) {
               return service->RemoveStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[20],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::StrategyNameRequest, ::otrader::DeleteStrategyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::StrategyNameRequest* req,
             ::otrader::DeleteStrategyResponse* resp) {
               return service->DeleteStrategy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[21],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EngineService::Service, ::otrader::Empty, ::otrader::StrategyHoldingsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::Empty* req,
             ::otrader::StrategyHoldingsResponse* resp) {
               return service->GetStrategyHoldings(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[22],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< EngineService::Service, ::otrader::StreamRequest, ::otrader::EngineStateUpdate>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::otrader::StreamRequest* req,
             ::grpc::ServerWriter<::otrader::EngineStateUpdate>* writer) {
               return service->StartBacktest(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EngineService_method_names[23],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< EngineService::Service, ::otrader::CommandRequest, ::otrader::CommandAck>(
          [](EngineService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::otrader::CommandRequest>* reader,
             ::otrader::CommandAck* resp) {
               return service->SendCommand(ctx, reader, resp);
             }, this)));
}

EngineService::Service::~Service() {
}

::grpc::Status EngineService::Service::GetStatus(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::EngineStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::ListStrategies(::grpc::ServerContext* context, const ::otrader::Empty* request, ::grpc::ServerWriter< ::otrader::StrategySummary>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::ConnectGateway(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::DisconnectGateway(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::StartMarketData(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::StopMarketData(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::StartStrategy(::grpc::ServerContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::StopStrategy(::grpc::ServerContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::StreamLogs(::grpc::ServerContext* context, const ::otrader::Empty* request, ::grpc::ServerWriter< ::otrader::LogLine>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::StreamStrategyUpdates(::grpc::ServerContext* context, const ::otrader::Empty* request, ::grpc::ServerWriter< ::otrader::StrategyUpdate>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::GetOrdersAndTrades(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::OrdersAndTradesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::ListPortfolios(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::ListPortfoliosResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::ListStrategyClasses(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::ListStrategyClassesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::GetStrategyClassDefaults(::grpc::ServerContext* context, const ::otrader::GetStrategyClassDefaultsRequest* request, ::otrader::GetStrategyClassDefaultsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::GetPortfoliosMeta(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::ListPortfoliosResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::GetRemovedStrategies(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::GetRemovedStrategiesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::AddStrategy(::grpc::ServerContext* context, const ::otrader::AddStrategyRequest* request, ::otrader::AddStrategyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::RestoreStrategy(::grpc::ServerContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::InitStrategy(::grpc::ServerContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::RemoveStrategy(::grpc::ServerContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::RemoveStrategyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::DeleteStrategy(::grpc::ServerContext* context, const ::otrader::StrategyNameRequest* request, ::otrader::DeleteStrategyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::GetStrategyHoldings(::grpc::ServerContext* context, const ::otrader::Empty* request, ::otrader::StrategyHoldingsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::StartBacktest(::grpc::ServerContext* context, const ::otrader::StreamRequest* request, ::grpc::ServerWriter< ::otrader::EngineStateUpdate>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status EngineService::Service::SendCommand(::grpc::ServerContext* context, ::grpc::ServerReader< ::otrader::CommandRequest>* reader, ::otrader::CommandAck* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace otrader

