# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.proto import otrader_engine_pb2 as otrader__engine__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in otrader_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineServiceStub(object):
    """Live engine control / query service."""

    def __init__(self, channel):
        """Args: channel: grpc.Channel."""
        self.GetStatus = channel.unary_unary(
                '/otrader.EngineService/GetStatus',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.EngineStatus.FromString,
                _registered_method=True)
        self.ListStrategies = channel.unary_stream(
                '/otrader.EngineService/ListStrategies',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.StrategySummary.FromString,
                _registered_method=True)
        self.ConnectGateway = channel.unary_unary(
                '/otrader.EngineService/ConnectGateway',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.Empty.FromString,
                _registered_method=True)
        self.DisconnectGateway = channel.unary_unary(
                '/otrader.EngineService/DisconnectGateway',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.Empty.FromString,
                _registered_method=True)
        self.StartMarketData = channel.unary_unary(
                '/otrader.EngineService/StartMarketData',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.Empty.FromString,
                _registered_method=True)
        self.StopMarketData = channel.unary_unary(
                '/otrader.EngineService/StopMarketData',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.Empty.FromString,
                _registered_method=True)
        self.StartStrategy = channel.unary_unary(
                '/otrader.EngineService/StartStrategy',
                request_serializer=otrader__engine__pb2.StrategyNameRequest.SerializeToString,
                response_deserializer=otrader__engine__pb2.Empty.FromString,
                _registered_method=True)
        self.StopStrategy = channel.unary_unary(
                '/otrader.EngineService/StopStrategy',
                request_serializer=otrader__engine__pb2.StrategyNameRequest.SerializeToString,
                response_deserializer=otrader__engine__pb2.Empty.FromString,
                _registered_method=True)
        self.StreamLogs = channel.unary_stream(
                '/otrader.EngineService/StreamLogs',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.LogLine.FromString,
                _registered_method=True)
        self.StreamStrategyUpdates = channel.unary_stream(
                '/otrader.EngineService/StreamStrategyUpdates',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.StrategyUpdate.FromString,
                _registered_method=True)
        self.GetOrdersAndTrades = channel.unary_unary(
                '/otrader.EngineService/GetOrdersAndTrades',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.OrdersAndTradesResponse.FromString,
                _registered_method=True)
        self.ListPortfolios = channel.unary_unary(
                '/otrader.EngineService/ListPortfolios',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.ListPortfoliosResponse.FromString,
                _registered_method=True)
        self.ListStrategyClasses = channel.unary_unary(
                '/otrader.EngineService/ListStrategyClasses',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.ListStrategyClassesResponse.FromString,
                _registered_method=True)
        self.GetStrategyClassDefaults = channel.unary_unary(
                '/otrader.EngineService/GetStrategyClassDefaults',
                request_serializer=otrader__engine__pb2.GetStrategyClassDefaultsRequest.SerializeToString,
                response_deserializer=otrader__engine__pb2.GetStrategyClassDefaultsResponse.FromString,
                _registered_method=True)
        self.GetPortfoliosMeta = channel.unary_unary(
                '/otrader.EngineService/GetPortfoliosMeta',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.ListPortfoliosResponse.FromString,
                _registered_method=True)
        self.GetRemovedStrategies = channel.unary_unary(
                '/otrader.EngineService/GetRemovedStrategies',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.GetRemovedStrategiesResponse.FromString,
                _registered_method=True)
        self.AddStrategy = channel.unary_unary(
                '/otrader.EngineService/AddStrategy',
                request_serializer=otrader__engine__pb2.AddStrategyRequest.SerializeToString,
                response_deserializer=otrader__engine__pb2.AddStrategyResponse.FromString,
                _registered_method=True)
        self.RestoreStrategy = channel.unary_unary(
                '/otrader.EngineService/RestoreStrategy',
                request_serializer=otrader__engine__pb2.StrategyNameRequest.SerializeToString,
                response_deserializer=otrader__engine__pb2.Empty.FromString,
                _registered_method=True)
        self.InitStrategy = channel.unary_unary(
                '/otrader.EngineService/InitStrategy',
                request_serializer=otrader__engine__pb2.StrategyNameRequest.SerializeToString,
                response_deserializer=otrader__engine__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveStrategy = channel.unary_unary(
                '/otrader.EngineService/RemoveStrategy',
                request_serializer=otrader__engine__pb2.StrategyNameRequest.SerializeToString,
                response_deserializer=otrader__engine__pb2.RemoveStrategyResponse.FromString,
                _registered_method=True)
        self.DeleteStrategy = channel.unary_unary(
                '/otrader.EngineService/DeleteStrategy',
                request_serializer=otrader__engine__pb2.StrategyNameRequest.SerializeToString,
                response_deserializer=otrader__engine__pb2.DeleteStrategyResponse.FromString,
                _registered_method=True)
        self.GetStrategyHoldings = channel.unary_unary(
                '/otrader.EngineService/GetStrategyHoldings',
                request_serializer=otrader__engine__pb2.Empty.SerializeToString,
                response_deserializer=otrader__engine__pb2.StrategyHoldingsResponse.FromString,
                _registered_method=True)


class EngineServiceServicer(object):
    """Live engine control / query service."""

    def GetStatus(self, request, context):
        """General status."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectGateway(self, request, context):
        """Live control."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectGateway(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartMarketData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopMarketData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStrategy(self, request, context):
        """Strategy control."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """Event streams (logs / strategy updates)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStrategyUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrdersAndTrades(self, request, context):
        """Main: orders/trades, portfolio list.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPortfolios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStrategyClasses(self, request, context):
        """Strategy: class list, portfolio meta, removed, defaults."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStrategyClassDefaults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPortfoliosMeta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRemovedStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddStrategy(self, request, context):
        """Strategy lifecycle."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStrategy(self, request, context):
        """C++: same as RemoveStrategy."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStrategyHoldings(self, request, context):
        """Strategy holdings."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.EngineStatus.SerializeToString,
            ),
            'ListStrategies': grpc.unary_stream_rpc_method_handler(
                    servicer.ListStrategies,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.StrategySummary.SerializeToString,
            ),
            'ConnectGateway': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectGateway,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.Empty.SerializeToString,
            ),
            'DisconnectGateway': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectGateway,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.Empty.SerializeToString,
            ),
            'StartMarketData': grpc.unary_unary_rpc_method_handler(
                    servicer.StartMarketData,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.Empty.SerializeToString,
            ),
            'StopMarketData': grpc.unary_unary_rpc_method_handler(
                    servicer.StopMarketData,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.Empty.SerializeToString,
            ),
            'StartStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStrategy,
                    request_deserializer=otrader__engine__pb2.StrategyNameRequest.FromString,
                    response_serializer=otrader__engine__pb2.Empty.SerializeToString,
            ),
            'StopStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStrategy,
                    request_deserializer=otrader__engine__pb2.StrategyNameRequest.FromString,
                    response_serializer=otrader__engine__pb2.Empty.SerializeToString,
            ),
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.LogLine.SerializeToString,
            ),
            'StreamStrategyUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStrategyUpdates,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.StrategyUpdate.SerializeToString,
            ),
            'GetOrdersAndTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrdersAndTrades,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.OrdersAndTradesResponse.SerializeToString,
            ),
            'ListPortfolios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPortfolios,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.ListPortfoliosResponse.SerializeToString,
            ),
            'ListStrategyClasses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStrategyClasses,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.ListStrategyClassesResponse.SerializeToString,
            ),
            'GetStrategyClassDefaults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategyClassDefaults,
                    request_deserializer=otrader__engine__pb2.GetStrategyClassDefaultsRequest.FromString,
                    response_serializer=otrader__engine__pb2.GetStrategyClassDefaultsResponse.SerializeToString,
            ),
            'GetPortfoliosMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPortfoliosMeta,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.ListPortfoliosResponse.SerializeToString,
            ),
            'GetRemovedStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRemovedStrategies,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.GetRemovedStrategiesResponse.SerializeToString,
            ),
            'AddStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStrategy,
                    request_deserializer=otrader__engine__pb2.AddStrategyRequest.FromString,
                    response_serializer=otrader__engine__pb2.AddStrategyResponse.SerializeToString,
            ),
            'RestoreStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreStrategy,
                    request_deserializer=otrader__engine__pb2.StrategyNameRequest.FromString,
                    response_serializer=otrader__engine__pb2.Empty.SerializeToString,
            ),
            'InitStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.InitStrategy,
                    request_deserializer=otrader__engine__pb2.StrategyNameRequest.FromString,
                    response_serializer=otrader__engine__pb2.Empty.SerializeToString,
            ),
            'RemoveStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveStrategy,
                    request_deserializer=otrader__engine__pb2.StrategyNameRequest.FromString,
                    response_serializer=otrader__engine__pb2.RemoveStrategyResponse.SerializeToString,
            ),
            'DeleteStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStrategy,
                    request_deserializer=otrader__engine__pb2.StrategyNameRequest.FromString,
                    response_serializer=otrader__engine__pb2.DeleteStrategyResponse.SerializeToString,
            ),
            'GetStrategyHoldings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategyHoldings,
                    request_deserializer=otrader__engine__pb2.Empty.FromString,
                    response_serializer=otrader__engine__pb2.StrategyHoldingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'otrader.EngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('otrader.EngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngineService(object):
    """Live engine control / query service."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/GetStatus',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.EngineStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/otrader.EngineService/ListStrategies',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.StrategySummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectGateway(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/ConnectGateway',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectGateway(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/DisconnectGateway',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/StartMarketData',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/StopMarketData',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/StartStrategy',
            otrader__engine__pb2.StrategyNameRequest.SerializeToString,
            otrader__engine__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/StopStrategy',
            otrader__engine__pb2.StrategyNameRequest.SerializeToString,
            otrader__engine__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/otrader.EngineService/StreamLogs',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.LogLine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStrategyUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/otrader.EngineService/StreamStrategyUpdates',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.StrategyUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrdersAndTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/GetOrdersAndTrades',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.OrdersAndTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPortfolios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/ListPortfolios',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.ListPortfoliosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStrategyClasses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/ListStrategyClasses',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.ListStrategyClassesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStrategyClassDefaults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/GetStrategyClassDefaults',
            otrader__engine__pb2.GetStrategyClassDefaultsRequest.SerializeToString,
            otrader__engine__pb2.GetStrategyClassDefaultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPortfoliosMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/GetPortfoliosMeta',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.ListPortfoliosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRemovedStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/GetRemovedStrategies',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.GetRemovedStrategiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/AddStrategy',
            otrader__engine__pb2.AddStrategyRequest.SerializeToString,
            otrader__engine__pb2.AddStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/RestoreStrategy',
            otrader__engine__pb2.StrategyNameRequest.SerializeToString,
            otrader__engine__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/InitStrategy',
            otrader__engine__pb2.StrategyNameRequest.SerializeToString,
            otrader__engine__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/RemoveStrategy',
            otrader__engine__pb2.StrategyNameRequest.SerializeToString,
            otrader__engine__pb2.RemoveStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/DeleteStrategy',
            otrader__engine__pb2.StrategyNameRequest.SerializeToString,
            otrader__engine__pb2.DeleteStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStrategyHoldings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/otrader.EngineService/GetStrategyHoldings',
            otrader__engine__pb2.Empty.SerializeToString,
            otrader__engine__pb2.StrategyHoldingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
